# Generated by Django 2.2.16 on 2022-05-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20220510_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.IntegerField(blank=True, verbose_name='Код подтверждения'),
        ),
    ]
