# Generated by Django 2.2.16 on 2022-05-13 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_auto_20220513_1722'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.TextField(blank=True, default='user', verbose_name='Роль'),
        ),
    ]
