# Generated by Django 2.2.16 on 2022-05-15 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20220513_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='confirmation_code',
            field=models.CharField(blank=True, max_length=4, verbose_name='Код подтверждения'),
        ),
    ]
